import type { Metadata } from "next";
import "@styles/globals.css";
import '@fontsource/comfortaa';
import '@fontsource/cousine';
import '@fontsource/days-one';
// import { Toaster } from "sonner";
import { Toaster } from "@/components/ui/toaster"
import { ErrorBoundary } from "next/dist/client/components/error-boundary";

export const metadata: Metadata = {
  title: "Trancendence",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body>
        {/* <div className="bg-red-500"> */}
        {/* <ErrorBoundary> */}
          {children}
          <Toaster />

        {/* </ErrorBoundary> */}
        {/* </div> */}
      </body>
    </html>
  );
}